# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node/service_for_sdk.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node/service_for_sdk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import contractID_pb2 as common_dot_contractID__pb2
from common import rpc_common_pb2 as common_dot_rpc__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anode/service_for_sdk.proto\x12\x03\x61pi\x1a\x17\x63ommon/contractID.proto\x1a\x17\x63ommon/rpc_common.proto\"J\n\x19SdkSendTransactionRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0c\n\x04sign\x18\x02 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\t\",\n\x15TxNotifyStreamRequest\x12\x13\n\x0b\x62lockHeight\x18\x01 \x01(\x04\":\n\x13TxNotifyStreamReply\x12\x13\n\x0b\x62lockHeight\x18\x01 \x01(\x04\x12\x0e\n\x06txHash\x18\x02 \x03(\t2\x81\x02\n\x10SdkInvokeService\x12\x30\n\x06invoke\x12\x15.api.SdkInvokeRequest\x1a\r.api.RpcReply\"\x00\x12/\n\x05query\x12\x15.api.SdkInvokeRequest\x1a\r.api.RpcReply\"\x00\x12\x42\n\x0fsendTransaction\x12\x1e.api.SdkSendTransactionRequest\x1a\r.api.RpcReply\"\x00\x12\x46\n\x08txNotify\x12\x1a.api.TxNotifyStreamRequest\x1a\x18.api.TxNotifyStreamReply\"\x00(\x01\x30\x01\x42\x35\n\x1f\x63n.mrray.raychain.sdk.grpc.nodeB\x10NodeServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node.service_for_sdk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cn.mrray.raychain.sdk.grpc.nodeB\020NodeServiceProtoP\001'
  _globals['_SDKSENDTRANSACTIONREQUEST']._serialized_start=85
  _globals['_SDKSENDTRANSACTIONREQUEST']._serialized_end=159
  _globals['_TXNOTIFYSTREAMREQUEST']._serialized_start=161
  _globals['_TXNOTIFYSTREAMREQUEST']._serialized_end=205
  _globals['_TXNOTIFYSTREAMREPLY']._serialized_start=207
  _globals['_TXNOTIFYSTREAMREPLY']._serialized_end=265
  _globals['_SDKINVOKESERVICE']._serialized_start=268
  _globals['_SDKINVOKESERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
