# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import rpc_common_pb2 as common_dot_rpc__common__pb2
from contract import service_for_node_pb2 as contract_dot_service__for__node__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contract/service_for_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContractServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.invoke = channel.unary_unary(
                '/api.ContractService/invoke',
                request_serializer=contract_dot_service__for__node__pb2.ContractRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.initContract = channel.unary_unary(
                '/api.ContractService/initContract',
                request_serializer=contract_dot_service__for__node__pb2.ContractRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.deployContract = channel.stream_unary(
                '/api.ContractService/deployContract',
                request_serializer=contract_dot_service__for__node__pb2.UploadContractRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)


class ContractServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def initContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deployContract(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContractServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.invoke,
                    request_deserializer=contract_dot_service__for__node__pb2.ContractRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'initContract': grpc.unary_unary_rpc_method_handler(
                    servicer.initContract,
                    request_deserializer=contract_dot_service__for__node__pb2.ContractRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'deployContract': grpc.stream_unary_rpc_method_handler(
                    servicer.deployContract,
                    request_deserializer=contract_dot_service__for__node__pb2.UploadContractRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.ContractService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.ContractService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContractService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ContractService/invoke',
            contract_dot_service__for__node__pb2.ContractRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def initContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.ContractService/initContract',
            contract_dot_service__for__node__pb2.ContractRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deployContract(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.ContractService/deployContract',
            contract_dot_service__for__node__pb2.UploadContractRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
