# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node/service_for_contract.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node/service_for_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import contractID_pb2 as common_dot_contractID__pb2
from common import rpc_common_pb2 as common_dot_rpc__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fnode/service_for_contract.proto\x12\x03\x61pi\x1a\x17\x63ommon/contractID.proto\x1a\x17\x63ommon/rpc_common.proto\"\xd4\x01\n\x14\x43ontractStateRequest\x12$\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x0f.api.ContractID\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12\x0c\n\x04sign\x18\x05 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x06 \x01(\t\x12\x1a\n\x12\x63hannel_identifier\x18\x07 \x01(\t\x12\r\n\x05table\x18\x08 \x01(\t\x12\x0b\n\x03sql\x18\t \x01(\t\x12\x12\n\nsql_params\x18\n \x01(\t\"\xaa\x01\n\x14\x43ontractCrossRequest\x12$\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x0f.api.ContractID\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x1a\n\x12\x63hannel_identifier\x18\x04 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x05 \x01(\t\x12\x1f\n\x06\x63\x61ller\x18\x06 \x03(\x0b\x32\x0f.api.ContractID2\xd8\x01\n\x13NodeContractService\x12?\n\x11getVersionedValue\x12\x19.api.ContractStateRequest\x1a\r.api.RpcReply\"\x00\x12\x42\n\x14getRdbVersionedValue\x12\x19.api.ContractStateRequest\x1a\r.api.RpcReply\"\x00\x12<\n\x0einvokeContract\x12\x19.api.ContractCrossRequest\x1a\r.api.RpcReply\"\x00\x42=\n\x1f\x63n.mrray.raychain.sdk.grpc.nodeB\x18NodeContractServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node.service_for_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cn.mrray.raychain.sdk.grpc.nodeB\030NodeContractServiceProtoP\001'
  _globals['_CONTRACTSTATEREQUEST']._serialized_start=91
  _globals['_CONTRACTSTATEREQUEST']._serialized_end=303
  _globals['_CONTRACTCROSSREQUEST']._serialized_start=306
  _globals['_CONTRACTCROSSREQUEST']._serialized_end=476
  _globals['_NODECONTRACTSERVICE']._serialized_start=479
  _globals['_NODECONTRACTSERVICE']._serialized_end=695
# @@protoc_insertion_point(module_scope)
