# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node/service_for_sdk_admin.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node/service_for_sdk_admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import contractID_pb2 as common_dot_contractID__pb2
from common import rpc_common_pb2 as common_dot_rpc__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n node/service_for_sdk_admin.proto\x12\x03\x61pi\x1a\x17\x63ommon/contractID.proto\x1a\x17\x63ommon/rpc_common.proto\"^\n\x11UpdateCertRequest\x12\x1a\n\x12\x63hannel_identifier\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\t\x12\x0c\n\x04sign\x18\x04 \x01(\t\"6\n\x16MsgNotifyStreamRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x0c\n\x04sign\x18\x02 \x01(\t\"L\n\x0e\x43ommandRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x0b\n\x03\x63md\x18\x03 \x01(\t\x12\x0c\n\x04sign\x18\x04 \x01(\t\"\'\n\x14MsgNotifyStreamReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xc2\x01\n\x15\x44\x65ployContractRequest\x12\x1a\n\x12\x63hannel_identifier\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\x12\x0c\n\x04sign\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12\x16\n\x0e\x63ontract_input\x18\x05 \x01(\t\x12\x11\n\tfile_name\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\x0c\x12\x11\n\tfile_size\x18\x08 \x01(\x03\x12\x0f\n\x07is_last\x18\t \x01(\x08\x32\xff\x03\n\x15SdkAdminInvokeService\x12\x37\n\rcreateChannel\x12\x15.api.SdkInvokeRequest\x1a\r.api.RpcReply\"\x00\x12=\n\x13\x63hainNetJoinChannel\x12\x15.api.SdkInvokeRequest\x1a\r.api.RpcReply\"\x00\x12=\n\x13\x63hainNetExitChannel\x12\x15.api.SdkInvokeRequest\x1a\r.api.RpcReply\"\x00\x12<\n\x11updateCertRequest\x12\x16.api.UpdateCertRequest\x1a\r.api.RpcReply\"\x00\x12I\n\tmsgNotify\x12\x1b.api.MsgNotifyStreamRequest\x1a\x19.api.MsgNotifyStreamReply\"\x00(\x01\x30\x01\x12/\n\x07\x63ommand\x12\x13.api.CommandRequest\x1a\r.api.RpcReply\"\x00\x12?\n\x0euploadContract\x12\x1a.api.DeployContractRequest\x1a\r.api.RpcReply\"\x00(\x01\x12\x34\n\nenrollCert\x12\x15.api.SdkInvokeRequest\x1a\r.api.RpcReply\"\x00\x42\x35\n\x1f\x63n.mrray.raychain.sdk.grpc.nodeB\x10NodeServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node.service_for_sdk_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cn.mrray.raychain.sdk.grpc.nodeB\020NodeServiceProtoP\001'
  _globals['_UPDATECERTREQUEST']._serialized_start=91
  _globals['_UPDATECERTREQUEST']._serialized_end=185
  _globals['_MSGNOTIFYSTREAMREQUEST']._serialized_start=187
  _globals['_MSGNOTIFYSTREAMREQUEST']._serialized_end=241
  _globals['_COMMANDREQUEST']._serialized_start=243
  _globals['_COMMANDREQUEST']._serialized_end=319
  _globals['_MSGNOTIFYSTREAMREPLY']._serialized_start=321
  _globals['_MSGNOTIFYSTREAMREPLY']._serialized_end=360
  _globals['_DEPLOYCONTRACTREQUEST']._serialized_start=363
  _globals['_DEPLOYCONTRACTREQUEST']._serialized_end=557
  _globals['_SDKADMININVOKESERVICE']._serialized_start=560
  _globals['_SDKADMININVOKESERVICE']._serialized_end=1071
# @@protoc_insertion_point(module_scope)
