# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/rpc_common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common/rpc_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import contractID_pb2 as common_dot_contractID__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommon/rpc_common.proto\x12\x03\x61pi\x1a\x17\x63ommon/contractID.proto\"J\n\x08RpcReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x0e\n\x06txHash\x18\x04 \x01(\t\"\xa5\x01\n\x10SdkInvokeRequest\x12$\n\x0b\x63ontract_id\x18\x01 \x01(\x0b\x32\x0f.api.ContractID\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x1a\n\x12\x63hannel_identifier\x18\x04 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x05 \x01(\t\x12\x10\n\x08\x61pp_type\x18\x06 \x01(\t\x12\x0c\n\x04sign\x18\x07 \x01(\tB%\n!cn.mrray.raychain.sdk.grpc.commonP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.rpc_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!cn.mrray.raychain.sdk.grpc.commonP\001'
  _globals['_RPCREPLY']._serialized_start=57
  _globals['_RPCREPLY']._serialized_end=131
  _globals['_SDKINVOKEREQUEST']._serialized_start=134
  _globals['_SDKINVOKEREQUEST']._serialized_end=299
# @@protoc_insertion_point(module_scope)
