# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common import rpc_common_pb2 as common_dot_rpc__common__pb2
from node import service_for_sdk_admin_pb2 as node_dot_service__for__sdk__admin__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in node/service_for_sdk_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SdkAdminInvokeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createChannel = channel.unary_unary(
                '/api.SdkAdminInvokeService/createChannel',
                request_serializer=common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.chainNetJoinChannel = channel.unary_unary(
                '/api.SdkAdminInvokeService/chainNetJoinChannel',
                request_serializer=common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.chainNetExitChannel = channel.unary_unary(
                '/api.SdkAdminInvokeService/chainNetExitChannel',
                request_serializer=common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.updateCertRequest = channel.unary_unary(
                '/api.SdkAdminInvokeService/updateCertRequest',
                request_serializer=node_dot_service__for__sdk__admin__pb2.UpdateCertRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.msgNotify = channel.stream_stream(
                '/api.SdkAdminInvokeService/msgNotify',
                request_serializer=node_dot_service__for__sdk__admin__pb2.MsgNotifyStreamRequest.SerializeToString,
                response_deserializer=node_dot_service__for__sdk__admin__pb2.MsgNotifyStreamReply.FromString,
                _registered_method=True)
        self.command = channel.unary_unary(
                '/api.SdkAdminInvokeService/command',
                request_serializer=node_dot_service__for__sdk__admin__pb2.CommandRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.uploadContract = channel.stream_unary(
                '/api.SdkAdminInvokeService/uploadContract',
                request_serializer=node_dot_service__for__sdk__admin__pb2.DeployContractRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)
        self.enrollCert = channel.unary_unary(
                '/api.SdkAdminInvokeService/enrollCert',
                request_serializer=common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
                response_deserializer=common_dot_rpc__common__pb2.RpcReply.FromString,
                _registered_method=True)


class SdkAdminInvokeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def chainNetJoinChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def chainNetExitChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCertRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def msgNotify(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadContract(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def enrollCert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SdkAdminInvokeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.createChannel,
                    request_deserializer=common_dot_rpc__common__pb2.SdkInvokeRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'chainNetJoinChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.chainNetJoinChannel,
                    request_deserializer=common_dot_rpc__common__pb2.SdkInvokeRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'chainNetExitChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.chainNetExitChannel,
                    request_deserializer=common_dot_rpc__common__pb2.SdkInvokeRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'updateCertRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCertRequest,
                    request_deserializer=node_dot_service__for__sdk__admin__pb2.UpdateCertRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'msgNotify': grpc.stream_stream_rpc_method_handler(
                    servicer.msgNotify,
                    request_deserializer=node_dot_service__for__sdk__admin__pb2.MsgNotifyStreamRequest.FromString,
                    response_serializer=node_dot_service__for__sdk__admin__pb2.MsgNotifyStreamReply.SerializeToString,
            ),
            'command': grpc.unary_unary_rpc_method_handler(
                    servicer.command,
                    request_deserializer=node_dot_service__for__sdk__admin__pb2.CommandRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'uploadContract': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadContract,
                    request_deserializer=node_dot_service__for__sdk__admin__pb2.DeployContractRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
            'enrollCert': grpc.unary_unary_rpc_method_handler(
                    servicer.enrollCert,
                    request_deserializer=common_dot_rpc__common__pb2.SdkInvokeRequest.FromString,
                    response_serializer=common_dot_rpc__common__pb2.RpcReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.SdkAdminInvokeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.SdkAdminInvokeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SdkAdminInvokeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SdkAdminInvokeService/createChannel',
            common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def chainNetJoinChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SdkAdminInvokeService/chainNetJoinChannel',
            common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def chainNetExitChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SdkAdminInvokeService/chainNetExitChannel',
            common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateCertRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SdkAdminInvokeService/updateCertRequest',
            node_dot_service__for__sdk__admin__pb2.UpdateCertRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def msgNotify(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/api.SdkAdminInvokeService/msgNotify',
            node_dot_service__for__sdk__admin__pb2.MsgNotifyStreamRequest.SerializeToString,
            node_dot_service__for__sdk__admin__pb2.MsgNotifyStreamReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SdkAdminInvokeService/command',
            node_dot_service__for__sdk__admin__pb2.CommandRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def uploadContract(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.SdkAdminInvokeService/uploadContract',
            node_dot_service__for__sdk__admin__pb2.DeployContractRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def enrollCert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.SdkAdminInvokeService/enrollCert',
            common_dot_rpc__common__pb2.SdkInvokeRequest.SerializeToString,
            common_dot_rpc__common__pb2.RpcReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
