# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node/service_for_p2p.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node/service_for_p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anode/service_for_p2p.proto\x12\x04node\"j\n\x08P2pReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x12\n\npacketType\x18\x04 \x01(\t\x12\x1a\n\x12\x63hannel_identifier\x18\x05 \x01(\t\"\x84\x01\n\nP2pRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0c\n\x04sign\x18\x02 \x01(\t\x12\x17\n\x0fnode_identifier\x18\x03 \x01(\t\x12\x12\n\npacketType\x18\x04 \x01(\t\x12\x1a\n\x12\x63hannel_identifier\x18\x05 \x01(\t\x12\x0e\n\x06msg_id\x18\x06 \x01(\t\"\x8c\x01\n\x0f\x43ontractRequest\x12\x1a\n\x12\x63hannel_identifier\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\x12\x0c\n\x04sign\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12\x11\n\tfile_name\x18\x05 \x01(\t\x12\x1b\n\x13\x63ontract_identifier\x18\x06 \x01(\t\"\\\n\x11\x43ontractFileChunk\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x12\n\nchunk_size\x18\x03 \x01(\x05\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\x32z\n\nP2pService\x12,\n\x06invoke\x12\x10.node.P2pRequest\x1a\x0e.node.P2pReply\"\x00\x12>\n\x08\x63ontract\x12\x15.node.ContractRequest\x1a\x17.node.ContractFileChunk\"\x00\x30\x01\x42-\n\x1f\x63n.mrray.raychain.sdk.grpc.nodeB\x08RpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node.service_for_p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cn.mrray.raychain.sdk.grpc.nodeB\010RpcProtoP\001'
  _globals['_P2PREPLY']._serialized_start=36
  _globals['_P2PREPLY']._serialized_end=142
  _globals['_P2PREQUEST']._serialized_start=145
  _globals['_P2PREQUEST']._serialized_end=277
  _globals['_CONTRACTREQUEST']._serialized_start=280
  _globals['_CONTRACTREQUEST']._serialized_end=420
  _globals['_CONTRACTFILECHUNK']._serialized_start=422
  _globals['_CONTRACTFILECHUNK']._serialized_end=514
  _globals['_P2PSERVICE']._serialized_start=516
  _globals['_P2PSERVICE']._serialized_end=638
# @@protoc_insertion_point(module_scope)
